/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AkunRouteImport } from './routes/akun'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGithubRouteImport } from './routes/api/github'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AkunRoute = AkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRoute = ApiGithubRouteImport.update({
  id: '/api/github',
  path: '/api/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akun': typeof AkunRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/prompt': typeof PromptRoute
  '/riwayat': typeof RiwayatRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/github': typeof ApiGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akun': typeof AkunRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/prompt': typeof PromptRoute
  '/riwayat': typeof RiwayatRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/github': typeof ApiGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akun': typeof AkunRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/prompt': typeof PromptRoute
  '/riwayat': typeof RiwayatRoute
  '/tools': typeof ToolsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/github': typeof ApiGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akun'
    | '/auth'
    | '/chat'
    | '/prompt'
    | '/riwayat'
    | '/tools'
    | '/api/chat'
    | '/api/github'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akun'
    | '/auth'
    | '/chat'
    | '/prompt'
    | '/riwayat'
    | '/tools'
    | '/api/chat'
    | '/api/github'
  id:
    | '__root__'
    | '/'
    | '/akun'
    | '/auth'
    | '/chat'
    | '/prompt'
    | '/riwayat'
    | '/tools'
    | '/api/chat'
    | '/api/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkunRoute: typeof AkunRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  PromptRoute: typeof PromptRoute
  RiwayatRoute: typeof RiwayatRoute
  ToolsRoute: typeof ToolsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGithubRoute: typeof ApiGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akun': {
      id: '/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AkunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github': {
      id: '/api/github'
      path: '/api/github'
      fullPath: '/api/github'
      preLoaderRoute: typeof ApiGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkunRoute: AkunRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  PromptRoute: PromptRoute,
  RiwayatRoute: RiwayatRoute,
  ToolsRoute: ToolsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGithubRoute: ApiGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
